### ISSUE TITLE
!atten produces wrong results when called without length

### ISSUE THREAD

**Issue by mweyland** [molo1134/qrmbot#47]
Example:
```
!atten RG-58/U 1000 MHz 1 m
<qrm> RG-58/U (50Ω) attenuation estimated at 1000 MHz: 24 dB/100 ft (78.74 dB/100 m); loss @length 1 m: 0.79 dB
!atten RG-58/U 1000 MHz
<qrm> 0.032808399 / m
```
This could easily be mistaken for an attenuation of 0.032808399 dB / m. The `!atten` syntax stipulates that a length must be used, so the second call is invalid. Maybe we could get an error instead of that weird number? In fact I tried to figure out where that came from and failed to find the line that prints the per-meter line...

**Comment by molo1134** [comment]
Fixed, thank you for the report!
