### ISSUE TITLE
Add the /slap command

### ISSUE THREAD

**Issue by nr0q** [molo1134/qrmbot#50]
There used to be a /slap IRC command that was popular on some IRC servers but seems to be missing in modern implementations. It would be cool if the qrmbot could implement it

example:
```
/slap Khaytsus
qrm: nr0q_radio slaps Khaytsus around a bit with a large trout.
```

/label feature-request

**Comment by molo1134** [comment]
That was a mIRC script.  Better to add that to your client.  It's not server-side.
