### ISSUE TITLE
Possible GDPR violation?

### ISSUE THREAD

**Issue by konaya** [molo1134/qrmbot#53]
The nicks.csv file is tying together callsigns (which count as personally identifiable information) with Reddit accounts without the users' explicit consent. Even if an entry is removed, it remains in the commit history which is publicly accessible. [Here's an example.](https://github.com/molo1134/qrmbot/commit/2f6d4796f82454a102c423f4c4911e6df22303c4) As GitHub is obliged to comply with GDPR while at the same time having no strong obligations towards one individual unpaid user, this could very well result in this repository getting nuked from orbit and the associated account getting suspended.

I'd suggest following [GitHub's instructions for scrubbing sensitive data from the repo](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) and resolving not to commit this file to the repo ever again.

**Comment by molo1134** [comment]
This is entirely self-reported data scraped from reddit posts, comments and flair.  If you don't want your reddit ID to be associated with a callsign, don't use your callsign on reddit.  Lastly, I am not in GDPR jurisdiction.
